controller_manager:
  ros__parameters:
    update_rate: 500
    use_sim_time: true

    legged_controller:
      type: legged/LeggedController

    motor_tester:
      type: test_tools/MotorTester

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    contact_tester:
      type: test_tools/ContactTester

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

imu_sensor_broadcaster:
  ros__parameters:
    remappings:
    - from: /imu_sensor_broadcaster/imu
      to: test_tools/imu_tester/imu
    use_sim_time: true
    sensor_name: imu
    frame_id: imu_link

legged_controller:
  ros__parameters:
    use_sim_time: true
    robotName: "legged_robot"
    taskFile: "/home/luo/Project/Horse/Luo_ros2_control/src/legged_bringup/resource/A1/config/task.info"
    urdfFile: "/home/luo/Project/Horse/Luo_ros2_control/src/legged_bringup/resource/A1/urdf/A1.urdf"
    referenceFile: "/home/luo/Project/Horse/Luo_ros2_control/src/legged_bringup/resource/A1/config/reference.info"
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
    imuName: imu
    visualize: true
    kp: 0.0
    kd: 1.0
    kf: 0.0

motor_tester:
  ros__parameters:
    use_sim_time: true
    joints:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE

contact_tester:
  ros__parameters:
    use_sim_time: true
    contactNames:
      - LF
      - LH
      - RF
      - RH

joint_state_broadcaster:
  ros__parameters:
    frame_id: base_link
    interfaces:
      - position
      - velocity
    joints: 
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
    publish_dynamic_joint_states: true
    use_local_topics: false
    use_urdf_to_filter: true